base:
   seed: 42
   device: "cuda"


data_fetch:
    dir: "data/processed"
    train_data_path: "data/processed/train/train_images.pt"
    train_labels_path: "data/processed/train/train_labels.txt"
    test_data_path: "data/processed/test/test_images.pt"
    test_labels_path: "data/processed/test/test_labels.txt"
    batch_size: 64

model_params:
    dir: "models/"

hyperparams:
    lr: 0.001
    epochs: 10
    momentum: 0.9