name: Continuous Deployment

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate CLI
        uses: google-github-actions/auth@v2
        with:
            project_id: ${{ secrets.GCP_PROJECT_NAME }}
            credentials_json: ${{secrets.GCP_SERVICE_ACCOUNT_KEY }}
  
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_NAME }}

      - name: Build Container
        run: |
          docker build -f dockerfiles/train_model.dockerfile . -t gcptrainapp:latest
        
      - name: Tag Container
        run: |
          docker tag gcptrainapp gcr.io/${{ secrets.GCP_PROJECT_NAME }}/gcptrainapp
    
      - name: Push Container
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_NAME }}/gcptrainapp

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy run \
            --image gcr.io/${{ secrets.GCP_PROJECT_NAME }}/gcptrainapp:latest \
            --region europe-north1 \
            --platform managed \
            --port 80 \
            --cpu 2 \
            --memory 8Gi \
            --allow-unauthenticated